# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QueueingCalculator.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QScrollArea, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(804, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(-1, -1, 801, 561))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 799, 559))
        self.frame = QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 391, 561))
        self.frame.setStyleSheet(u"background-color: rgb(85, 255, 255);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(180, 120, 41, 31))
        font = QFont()
        font.setFamilies([u"Rockwell Extra Bold"])
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setPixmap(QPixmap(u"icons/mk.svg"))
        self.label.setScaledContents(True)
        self.lbl_llegada = QLabel(self.frame)
        self.lbl_llegada.setObjectName(u"lbl_llegada")
        self.lbl_llegada.setGeometry(QRect(60, 160, 101, 20))
        font1 = QFont()
        font1.setFamilies([u"MS PGothic"])
        font1.setBold(True)
        self.lbl_llegada.setFont(font1)
        self.lbl_servicio = QLabel(self.frame)
        self.lbl_servicio.setObjectName(u"lbl_servicio")
        self.lbl_servicio.setGeometry(QRect(260, 160, 101, 20))
        self.lbl_servicio.setFont(font1)
        self.lbl_numeroServicio = QLabel(self.frame)
        self.lbl_numeroServicio.setObjectName(u"lbl_numeroServicio")
        self.lbl_numeroServicio.setGeometry(QRect(60, 260, 141, 16))
        self.lbl_numeroServicio.setFont(font1)
        self.btn_calcular = QPushButton(self.frame)
        self.btn_calcular.setObjectName(u"btn_calcular")
        self.btn_calcular.setGeometry(QRect(40, 360, 331, 41))
        font2 = QFont()
        font2.setFamilies([u"Rockwell Extra Bold"])
        font2.setPointSize(16)
        font2.setBold(True)
        self.btn_calcular.setFont(font2)
        self.btn_calcular.setStyleSheet(u"background-color: rgb(255, 21, 255);")
        icon = QIcon()
        icon.addFile(u"icons/calculating.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_calcular.setIcon(icon)
        self.btn_calcular.setIconSize(QSize(25, 25))
        self.lineEdit_llegada = QLineEdit(self.frame)
        self.lineEdit_llegada.setObjectName(u"lineEdit_llegada")
        self.lineEdit_llegada.setGeometry(QRect(40, 190, 113, 22))
        self.lineEdit_llegada.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_servicio = QLineEdit(self.frame)
        self.lineEdit_servicio.setObjectName(u"lineEdit_servicio")
        self.lineEdit_servicio.setGeometry(QRect(250, 190, 113, 22))
        self.lineEdit_servicio.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_numeroServicio = QLineEdit(self.frame)
        self.lineEdit_numeroServicio.setObjectName(u"lineEdit_numeroServicio")
        self.lineEdit_numeroServicio.setGeometry(QRect(40, 290, 321, 31))
        self.lineEdit_numeroServicio.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 260, 21, 16))
        self.label_3.setFont(font1)
        self.label_3.setPixmap(QPixmap(u"icons/k.svg"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 160, 21, 21))
        self.label_4.setPixmap(QPixmap(u"icons/lambda.svg"))
        self.label_4.setScaledContents(True)
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(240, 160, 21, 21))
        self.label_6.setPixmap(QPixmap(u"icons/mu.svg"))
        self.label_6.setScaledContents(True)
        self.btn_limpiar = QPushButton(self.frame)
        self.btn_limpiar.setObjectName(u"btn_limpiar")
        self.btn_limpiar.setGeometry(QRect(40, 410, 331, 41))
        self.btn_limpiar.setFont(font2)
        self.btn_limpiar.setStyleSheet(u"background-color: rgb(255, 21, 255);")
        icon1 = QIcon()
        icon1.addFile(u"icons/cleaning.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_limpiar.setIcon(icon1)
        self.btn_limpiar.setIconSize(QSize(25, 25))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(150, 90, 101, 21))
        self.label_7.setFont(font)
        self.frame_2 = QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(389, 0, 411, 561))
        self.frame_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.lbl_solucion = QLabel(self.frame_2)
        self.lbl_solucion.setObjectName(u"lbl_solucion")
        self.lbl_solucion.setGeometry(QRect(130, 20, 151, 31))
        self.lbl_solucion.setFont(font)
        self.label_P = QLabel(self.frame_2)
        self.label_P.setObjectName(u"label_P")
        self.label_P.setGeometry(QRect(20, 60, 381, 61))
        font3 = QFont()
        font3.setFamilies([u"Rockwell Extra Bold"])
        font3.setPointSize(9)
        font3.setBold(True)
        self.label_P.setFont(font3)
        self.label_P.setStyleSheet(u"background-color: rgb(0, 255, 255);")
        self.label_P0 = QLabel(self.frame_2)
        self.label_P0.setObjectName(u"label_P0")
        self.label_P0.setGeometry(QRect(20, 140, 381, 61))
        self.label_P0.setFont(font3)
        self.label_P0.setStyleSheet(u"background-color: rgb(0, 255, 255);")
        self.label_Wq = QLabel(self.frame_2)
        self.label_Wq.setObjectName(u"label_Wq")
        self.label_Wq.setGeometry(QRect(20, 300, 381, 61))
        self.label_Wq.setFont(font3)
        self.label_Wq.setStyleSheet(u"background-color: rgb(0, 255, 255);")
        self.label_Lq = QLabel(self.frame_2)
        self.label_Lq.setObjectName(u"label_Lq")
        self.label_Lq.setGeometry(QRect(20, 220, 381, 61))
        self.label_Lq.setFont(font3)
        self.label_Lq.setStyleSheet(u"background-color: rgb(0, 255, 255);")
        self.label_Ws = QLabel(self.frame_2)
        self.label_Ws.setObjectName(u"label_Ws")
        self.label_Ws.setGeometry(QRect(20, 460, 381, 61))
        self.label_Ws.setFont(font3)
        self.label_Ws.setStyleSheet(u"background-color: rgb(0, 255, 255);")
        self.label_Ls = QLabel(self.frame_2)
        self.label_Ls.setObjectName(u"label_Ls")
        self.label_Ls.setGeometry(QRect(20, 380, 381, 61))
        self.label_Ls.setFont(font3)
        self.label_Ls.setStyleSheet(u"background-color: rgb(0, 255, 255);")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.lbl_llegada.setText(QCoreApplication.translate("MainWindow", u"Tasa de llegada", None))
        self.lbl_servicio.setText(QCoreApplication.translate("MainWindow", u"Tasa de servicio", None))
        self.lbl_numeroServicio.setText(QCoreApplication.translate("MainWindow", u" N\u00famero de servidores", None))
        self.btn_calcular.setText(QCoreApplication.translate("MainWindow", u"Calcular", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_6.setText("")
        self.btn_limpiar.setText(QCoreApplication.translate("MainWindow", u" Limpiar", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"M/M/K", None))
        self.lbl_solucion.setText(QCoreApplication.translate("MainWindow", u"Soluci\u00f3n", None))
        self.label_P.setText("")
        self.label_P0.setText("")
        self.label_Wq.setText("")
        self.label_Lq.setText("")
        self.label_Ws.setText("")
        self.label_Ls.setText("")
    # retranslateUi

